pluginManagement {
    includeBuild("build-logic")
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
rootProject.name = "Asteria"

include(
    "asteria-core",
    "asteria-actor",
    "asteria-message",
    "asteria-protobuf",
    "asteria-observability-core",
    "asteria-observability-opentelemetry",
    "asteria-rpc",
    "asteria-rpc-protobuf",
    "asteria-rpc-protobuf-generator",
    "asteria-broadcast",
    "asteria-broadcast-protobuf",
    "asteria-broadcast-pekko",
    "asteria-script-core",
    "asteria-script-job",
    "asteria-script-job-spring-boot-starter",
    "asteria-script-job-mongodb",
    "asteria-script-job-mongodb-spring-boot-starter",
    "asteria-script-protobuf",
    "asteria-script-pekko",
    "asteria-script-engine-jar",
    "asteria-script-engine-groovy",
    "asteria-cluster-pekko",
    "asteria-cluster-pekko-management",
    "asteria-cluster-pekko-kubernetes",
    "asteria-gm-core",
    "asteria-gm-spring-boot-starter",
    "asteria-gm-script",
    "asteria-gm-script-spring-boot-starter",
    "asteria-gm-config",
    "asteria-gm-config-spring-boot-starter",
    "asteria-gm-cluster",
    "asteria-gm-cluster-spring-boot-starter",
    "asteria-gm-cluster-pekko",
    "asteria-gm-cluster-pekko-management",
    "asteria-gm-cluster-pekko-management-spring-boot-starter",
    "asteria-gateway-core",
    "asteria-gateway-pekko",
    "asteria-protocol-protobuf",
    "asteria-protocol-protobuf-generator",
    "asteria-protocol-protobuf-gradle-plugin",
    "asteria-gateway-netty",
    "asteria-persistence",
    "asteria-persistence-mongodb",
    "asteria-game-utils",
    "asteria-config",
    "asteria-config-annotations",
    "asteria-config-gradle-plugin",
    "asteria-config-ksp",
    "asteria-config-luban",
    "asteria-config-center",
    "asteria-config-center-zookeeper",
    "asteria-config-center-etcd",
    "asteria-config-center-nacos",
    "asteria-cluster-config",
    "asteria-starter",
)

mapOf(
    "asteria-core" to "foundation/asteria-core",
    "asteria-actor" to "foundation/asteria-actor",
    "asteria-message" to "foundation/asteria-message",
    "asteria-protobuf" to "foundation/asteria-protobuf",
    "asteria-observability-core" to "observability/asteria-observability-core",
    "asteria-observability-opentelemetry" to "observability/asteria-observability-opentelemetry",
    "asteria-rpc" to "rpc/asteria-rpc",
    "asteria-rpc-protobuf" to "rpc/asteria-rpc-protobuf",
    "asteria-rpc-protobuf-generator" to "rpc/asteria-rpc-protobuf-generator",
    "asteria-broadcast" to "broadcast/asteria-broadcast",
    "asteria-broadcast-protobuf" to "broadcast/asteria-broadcast-protobuf",
    "asteria-broadcast-pekko" to "broadcast/asteria-broadcast-pekko",
    "asteria-script-core" to "script/asteria-script-core",
    "asteria-script-job" to "script/asteria-script-job",
    "asteria-script-job-spring-boot-starter" to "script/asteria-script-job-spring-boot-starter",
    "asteria-script-job-mongodb" to "script/asteria-script-job-mongodb",
    "asteria-script-job-mongodb-spring-boot-starter" to "script/asteria-script-job-mongodb-spring-boot-starter",
    "asteria-script-protobuf" to "script/asteria-script-protobuf",
    "asteria-script-pekko" to "script/asteria-script-pekko",
    "asteria-script-engine-jar" to "script/asteria-script-engine-jar",
    "asteria-script-engine-groovy" to "script/asteria-script-engine-groovy",
    "asteria-config" to "config/asteria-config",
    "asteria-config-annotations" to "config/asteria-config-annotations",
    "asteria-config-gradle-plugin" to "config/asteria-config-gradle-plugin",
    "asteria-config-ksp" to "config/asteria-config-ksp",
    "asteria-config-luban" to "config/asteria-config-luban",
    "asteria-config-center" to "config/asteria-config-center",
    "asteria-config-center-zookeeper" to "config/asteria-config-center-zookeeper",
    "asteria-config-center-etcd" to "config/asteria-config-center-etcd",
    "asteria-config-center-nacos" to "config/asteria-config-center-nacos",
    "asteria-cluster-config" to "config/asteria-cluster-config",
    "asteria-gm-core" to "gm/asteria-gm-core",
    "asteria-gm-spring-boot-starter" to "gm/asteria-gm-spring-boot-starter",
    "asteria-gm-script" to "gm/asteria-gm-script",
    "asteria-gm-script-spring-boot-starter" to "gm/asteria-gm-script-spring-boot-starter",
    "asteria-gm-config" to "gm/asteria-gm-config",
    "asteria-gm-config-spring-boot-starter" to "gm/asteria-gm-config-spring-boot-starter",
    "asteria-gm-cluster" to "gm/asteria-gm-cluster",
    "asteria-gm-cluster-spring-boot-starter" to "gm/asteria-gm-cluster-spring-boot-starter",
    "asteria-gm-cluster-pekko" to "gm/asteria-gm-cluster-pekko",
    "asteria-gm-cluster-pekko-management" to "gm/asteria-gm-cluster-pekko-management",
    "asteria-gm-cluster-pekko-management-spring-boot-starter" to "gm/asteria-gm-cluster-pekko-management-spring-boot-starter",
    "asteria-gateway-core" to "gateway/asteria-gateway-core",
    "asteria-gateway-pekko" to "gateway/asteria-gateway-pekko",
    "asteria-protocol-protobuf-generator" to "asteria-protocol-protobuf-generator",
    "asteria-protocol-protobuf-gradle-plugin" to "asteria-protocol-protobuf-gradle-plugin",
    "asteria-game-utils" to "utils/asteria-game-utils",
).forEach { (name, path) ->
    project(":$name").projectDir = file(path)
}
