pekko.actor {
  serializers {
    asteria-entity-waker = "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerSerializer"
  }

  serialization-bindings {
    "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerCommand" = asteria-entity-waker
    "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerStatus" = asteria-entity-waker
  }
}
