pekko.actor {
  serializers {
    asteria-entity-waker = "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerSerializer"
    asteria-cluster-config-control = "io.github.realmlabs.asteria.cluster.pekko.PekkoClusterConfigControlSerializer"
  }

  serialization-bindings {
    "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerCommand" = asteria-entity-waker
    "io.github.realmlabs.asteria.cluster.pekko.PekkoEntityWakerStatus" = asteria-entity-waker
    "io.github.realmlabs.asteria.cluster.pekko.PekkoClusterConfigControlMessage" = asteria-cluster-config-control
    "io.github.realmlabs.asteria.cluster.config.ClusterConfigNodeStatus" = asteria-cluster-config-control
    "io.github.realmlabs.asteria.cluster.config.ClusterConfigNodeReloadResult" = asteria-cluster-config-control
  }
}
