pekko.actor {
  serializers {
    asteria-script = "io.github.realmlabs.asteria.script.pekko.PekkoScriptSerializer"
  }

  serialization-bindings {
    "io.github.realmlabs.asteria.script.ScriptExecutionCommand" = asteria-script
    "io.github.realmlabs.asteria.script.ScriptExecutionResult" = asteria-script
    "io.github.realmlabs.asteria.script.pekko.ExecuteNodeScript" = asteria-script
    "io.github.realmlabs.asteria.script.pekko.ExecuteActorScript" = asteria-script
    "io.github.realmlabs.asteria.script.pekko.ExecuteEntityActorScript" = asteria-script
  }
}
