dependencies {
    api(project(":asteria-core"))
    api(project(":asteria-actor"))
    api(project(":asteria-message"))
    api(project(":asteria-rpc"))
    api(project(":asteria-rpc-protobuf"))
    api(project(":asteria-script-core"))
    api(project(":asteria-script-job"))
    api(project(":asteria-script-protobuf"))
    api(project(":asteria-script-pekko"))
    api(project(":asteria-script-engine-jar"))
    api(project(":asteria-script-engine-groovy"))
    api(project(":asteria-cluster-pekko"))
    api(project(":asteria-protocol-protobuf"))
    api(project(":asteria-gateway-netty"))
    api(project(":asteria-persistence"))
    api(project(":asteria-config"))
}
