pekko.actor {
  serializers {
    asteria-patch-control = "io.github.realmlabs.asteria.patch.pekko.PekkoPatchControlSerializer"
  }

  serialization-bindings {
    "io.github.realmlabs.asteria.patch.pekko.PekkoPatchControlMessage" = asteria-patch-control
    "io.github.realmlabs.asteria.patch.pekko.PekkoPatchDisableResult" = asteria-patch-control
    "io.github.realmlabs.asteria.patch.PatchNode" = asteria-patch-control
    "io.github.realmlabs.asteria.patch.PatchApplyResult" = asteria-patch-control
  }
}
