package io.github.realmlabs.asteria.config.annotations

import kotlin.reflect.KClass

/**
 * Marks a config row type or schema marker as a generated table accessor source.
 *
 * Put this annotation directly on a row class when the row source can be annotated:
 *
 * ```kotlin
 * @AsteriaConfigTable(name = "items", keyType = Int::class)
 * data class ItemConfig(val id: Int, val name: String)
 *
 * @AsteriaConfigTable(name = "rank_rewards", shape = AsteriaConfigTableShape.LIST)
 * data class RankRewardConfig(val rank: Int, val itemId: Int)
 * ```
 *
 * If the row class is generated by another tool and cannot be annotated, place the annotation on a
 * marker object and set [rowType]:
 *
 * ```kotlin
 * @AsteriaConfigTable(name = "items", keyType = Int::class, rowType = ItemConfig::class)
 * object ItemsTable
 * ```
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class AsteriaConfigTable(
    /**
     * Stable table name inside [io.github.realmlabs.asteria.config.ConfigSnapshot].
     */
    val name: String,
    /**
     * Table shape used by generated refs and accessors.
     */
    val shape: AsteriaConfigTableShape = AsteriaConfigTableShape.KEYED,
    /**
     * Row id type. Required when [shape] is [AsteriaConfigTableShape.KEYED].
     */
    val keyType: KClass<*> = Nothing::class,
    /**
     * Row object type. Leave as default when this annotation is placed on the row class itself.
     */
    val rowType: KClass<*> = Nothing::class,
    /**
     * Optional concrete table implementation returned by generated accessors.
     *
     * Leave this unset to return shape-level interfaces such as `KeyedConfigTable<K, R>`. Set it
     * when callers need implementation APIs, for example `MapConfigTable<K, R>` or
     * `OrderedMapConfigTable<K, R>`.
     */
    val tableType: KClass<*> = Nothing::class,
    /**
     * Optional generated reference property name, for example `Items`.
     */
    val refName: String = "",
    /**
     * Optional generated accessor property/function name, for example `items`.
     */
    val propertyName: String = "",
)

enum class AsteriaConfigTableShape {
    KEYED,
    LIST,
    SINGLETON,
}
