package io.github.realmlabs.asteria.config.annotations

import kotlin.reflect.KClass

/**
 * Marks a config row type or schema marker as a generated table accessor source.
 *
 * Put this annotation directly on a row class when the row source can be annotated:
 *
 * ```kotlin
 * @AsteriaConfigTable(name = "items", keyType = Int::class)
 * data class ItemConfig(val id: Int, val name: String)
 * ```
 *
 * If the row class is generated by another tool and cannot be annotated, place the annotation on a
 * marker object and set [rowType]:
 *
 * ```kotlin
 * @AsteriaConfigTable(name = "items", keyType = Int::class, rowType = ItemConfig::class)
 * object ItemsTable
 * ```
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class AsteriaConfigTable(
    /**
     * Stable table name inside [io.github.realmlabs.asteria.config.ConfigSnapshot].
     */
    val name: String,
    /**
     * Row id type.
     */
    val keyType: KClass<*>,
    /**
     * Row object type. Leave as default when this annotation is placed on the row class itself.
     */
    val rowType: KClass<*> = Nothing::class,
    /**
     * Optional generated reference property name, for example `Items`.
     */
    val refName: String = "",
    /**
     * Optional generated accessor property/function name, for example `items`.
     */
    val propertyName: String = "",
)
